### ISSUE TITLE
Error in userprofiles.list(client.id,client.secret) 

### ISSUE THREAD

**Issue by kairos35** [WillemPaling/RDoubleClick#2]
hi, sorry, have another issue. 

DCAuth(client.id,client.secret) works fine and authentification is no problem

BUT: when running 
     profiles <- userprofiles.list(client.id,client.secret) 
R produces an error

Error in fromJSON(api.request(req.url)) : 
  could not find function "api.request"
Called from: fromJSON(api.request(req.url))
Browse[1]> 

![image](https://cloud.githubusercontent.com/assets/10060347/24039007/fe33cc28-0b03-11e7-8ccd-707b6f36ceb4.png)

I am using the the function:

userprofiles.list <- function(client.id,client.secret){
   req.url <- "https://www.googleapis.com/dfareporting/v2.7/userprofiles"
  response <- fromJSON(api.request(req.url))
  
  return(response$items)
  }

and also tried changing v2.7 back to v2.5.
Thanks for any advice!

**Comment by WillemPaling** [comment]
I just updated to use v2.7 – that's not the issue.
I did get the same issue, as I haven't used this in a while.
After you create the client id and secret in the google APIs console, you also have to go in and enable the DCM Reporting API.

GO here: https://console.developers.google.com/apis/dashboard
Select your project.
Then click "enable API".
Then click on "DCM/DFA Reporting And Trafficking API"
Then click on "enable"
