### ISSUE TITLE
Reports.run is throwing "Error: All components of body must be named"

### ISSUE THREAD

**Issue by KrisM-tor** [WillemPaling/RDoubleClick#4]
Hi Willem,

wondering if you could possibly help me out. I'm attempting to use the report.run function however I'm getting a "Error: All components of body must be named". Any ideas for what's causing this? From what I gathered it's something potentially to do with the httr version?

Thank you,
-K

**Comment by WillemPaling** [comment]
Hi Kristopher – can you post the code that you're running and I can try to debug on my DoubleClick account.

I don't use this library regularly anymore, but will try to find out what the issue is.

**Comment by KrisM-tor** [comment]
Thanks for the response! It's very much appreciated. From what I understand the function is 

report <- reports.run(profileId, reportId) 

Is there something else missing to this function? I've inputted a valid profileId + reportId and authenticated the session (I'm able to use the files.get function without issues...). Is there something else you're using in place of this by the way?


Many thanks!

**Comment by WillemPaling** [comment]
It looks like it's probably a deprecated call to HTTR.
The way you are calling it is fine.

Were you able to successfully run files.list ?

**Comment by WillemPaling** [comment]
I've been able to replicate and resolve the issue.
Also updating to use the v3.0 API, which breaks files.list and introduces reports.list.
Hopefully I will have an update that fixes your issue in the next day or two.

**Comment by WillemPaling** [comment]
Can you try reinstalling from here and re-running your code?

**Comment by KrisM-tor** [comment]
Worked like a charm! The reports.run function is now working as intended. I feel like I need to go a bit deeper in understanding how this package makes the calls so that I know how to troubleshoot the next time. Your help was very much appreciated! Cheers

**Comment by WillemPaling** [comment]
Awesome. I'll close the issue.

**Comment by Arbaaz5678** [comment]
Hi Willem, having trouble with DCAuth command, when i run DCAuth(client.id, client.secret), it tells me command not found !!!

**Comment by Arbaaz5678** [comment]
Hi willem, when i run the DCAuth(client.id, client.secret), it tells me could not find the function "DCAuth".

**Comment by WillemPaling** [comment]
Have you installed the package successfully? Can you call other functions?

**Comment by Arbaaz5678** [comment]
library(devtools)
install_github("WillemPaling/RDoubleClick")
client.id <- "yourclientid.apps.googleusercontent.com"
client.secret <- "yourclientsecret"

then when i ran the function
DCAuth(client.id, client.secret) i got that error

**Comment by Arbaaz5678** [comment]
still getting the same error

**Comment by WillemPaling** [comment]
It sounds like the package is not installed. 
Do you get any output from this?

install_github("WillemPaling/RDoubleClick")

**Comment by Arbaaz5678** [comment]
okey ill uninstall and reinstall the package once again
